runtime: php55
api_version: 1

runtime_config:
  enable_stackdriver_integration: true

handlers:
- url: /
  script: index.php

- url: /(.+\.php)$
  script: \1
  
- url: /uploads
  static_dir: uploads

- url: /(.+\.js)$
  script: \1
  
- url: /css
  static_dir: css
  
- url: /images
  static_dir: images