runtime: php55
api_version: 1

handlers:
- url: /
  script: index.php

- url: /(.+\.php)$
  script: \1
  

- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: uploads/\1
  upload: uploads/(.*\.(bmp|gif|ico|jpeg|jpg|png))

- url: /(.+\.js)$
  script: \1